# 主流网站密码规则预设
WEBSITE_PRESETS = {
    "自定义": {
        "site_name": "",
        "url": "",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "",
    },
    "Google": {
        "site_name": "Google",
        "url": "https://accounts.google.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Google 要求至少 8 位，建议 12 位以上，支持所有字符",
    },
    "YouTube": {
        "site_name": "YouTube",
        "url": "https://www.youtube.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "与 Google 账号共用密码规则",
    },
    "GitHub": {
        "site_name": "GitHub",
        "url": "https://github.com",
        "length": 20,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "GitHub 要求至少 8 位，建议 15 位以上",
    },
    "Microsoft": {
        "site_name": "Microsoft",
        "url": "https://account.microsoft.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Microsoft 要求至少 8 位，区分大小写",
    },
    "Apple ID": {
        "site_name": "Apple ID",
        "url": "https://appleid.apple.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Apple ID 要求至少 8 位，不能含空格",
    },
    "Twitter/X": {
        "site_name": "Twitter/X",
        "url": "https://x.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "X 要求至少 8 位",
    },
    "Facebook": {
        "site_name": "Facebook",
        "url": "https://www.facebook.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Facebook 要求至少 6 位",
    },
    "Instagram": {
        "site_name": "Instagram",
        "url": "https://www.instagram.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Instagram 要求至少 6 位",
    },
    "Amazon": {
        "site_name": "Amazon",
        "url": "https://www.amazon.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Amazon 要求至少 6 位",
    },
    "Netflix": {
        "site_name": "Netflix",
        "url": "https://www.netflix.com",
        "length": 12,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": False,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Netflix 不支持特殊字符",
    },
    "PayPal": {
        "site_name": "PayPal",
        "url": "https://www.paypal.com",
        "length": 20,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "PayPal 要求至少 8 位，建议强密码",
    },
    "Steam": {
        "site_name": "Steam",
        "url": "https://store.steampowered.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "Steam 要求至少 8 位",
    },
    "QQ": {
        "site_name": "QQ",
        "url": "https://im.qq.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "QQ 密码要求 8-16 位",
    },
    "微信": {
        "site_name": "微信",
        "url": "",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "微信密码要求 8-16 位",
    },
    "淘宝/支付宝": {
        "site_name": "淘宝/支付宝",
        "url": "https://www.alipay.com",
        "length": 20,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "支付宝要求至少 8 位，建议强密码",
    },
    "百度": {
        "site_name": "百度",
        "url": "https://www.baidu.com",
        "length": 14,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "百度密码要求 6-14 位",
    },
    "Bilibili": {
        "site_name": "Bilibili",
        "url": "https://www.bilibili.com",
        "length": 16,
        "use_upper": True,
        "use_lower": True,
        "use_digits": True,
        "use_special": True,
        "custom_chars": "",
        "exclude_similar": False,
        "custom_mode": "only",
        "shuffle_custom": True,
        "note": "B站密码要求 6-16 位",
    },
}
